import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {validateRange} from '../assets/domain.js';
test('migracja i rzeczywiste transakcje PostgreSQL',async t=>{
 const pg=new PGlite();
 await pg.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);`);
 const sql=await readFile(new URL('../supabase/001_podocare.sql',import.meta.url),'utf8');await pg.exec(sql);
 const actor=crypto.randomUUID(),other=crypto.randomUUID(),patient=crypto.randomUUID();
 await pg.query('insert into auth.users(id) values ($1),($2)',[actor,other]);await pg.query('insert into podo_admins values($1)',[actor]);
 const action=async(a,d,user=actor)=>(await pg.query('select podo_action($1,$2::jsonb,$3) result',[a,JSON.stringify(d),user])).rows[0].result;
 await t.test('nie-admin nie może wykonywać operacji',async()=>{await assert.rejects(action('patient',{id:patient,name:'Test'},other),/Brak uprawnień/);});
 await action('patient',{id:patient,name:'Pacjent Fikcyjny',email:'test@example.invalid',profile:{allergies:'lateks'}});
 const aid=crypto.randomUUID(),b={id:aid,patient_id:patient,service_id:'basic',...validateRange('2036-09-28','10:00','11:00')};
 await t.test('potwierdzenie tworzy wizytę i 2 zadania pocztowe atomowo',async()=>{await action('book',b);assert.equal((await pg.query('select count(*)::int n from podo_mail')).rows[0].n,2);});
 await t.test('retry nie dubluje wizyty ani e-maili',async()=>{const r=await action('book',b);assert.equal(r.reused,true);assert.equal((await pg.query('select count(*)::int n from podo_appointments')).rows[0].n,1);});
 await t.test('kolizja zakresów blokowana po stronie DB',async()=>{await assert.rejects(action('book',{...b,id:crypto.randomUUID()}),/zajęty/);});
 await t.test('30 minut i granice godzin wymuszane przez DB',async()=>{await assert.rejects(action('book',{...b,id:crypto.randomUUID(),starts_at:'2036-09-28T05:00:00Z'}),/zakres/);await assert.rejects(action('book',{...b,id:crypto.randomUUID(),starts_at:'2036-09-28T12:15:00Z',ends_at:'2036-09-28T13:00:00Z'}),/zakres/);});
 await t.test('zmiana profilu nie podmienia danych rezerwacji',async()=>{await action('patient',{id:patient,name:'Zmienione Dane',email:'changed@example.invalid',profile:{allergies:'lateks'}});const a=(await pg.query('select * from podo_appointments where id=$1',[aid])).rows[0];assert.equal(a.patient_email,'test@example.invalid');assert.equal(a.patient_name,'Pacjent Fikcyjny');});
 await t.test('anulowanie odwołuje kolejkę i zwalnia termin',async()=>{await action('cancel',{id:aid});assert.equal((await pg.query("select count(*)::int n from podo_mail where kind in ('confirmed','reminder') and state='cancelled'")).rows[0].n,2);await action('book',{...b,id:crypto.randomUUID()});});
 const a2=(await pg.query("select id from podo_appointments where status='confirmed'")).rows[0].id;
 const encounter={id:crypto.randomUUID(),patient_id:patient,appointment_id:a2,observations:'Obserwacja',performed:'Dokumentacja testowa',aftercare:'Indywidualne zalecenia',pain:0,amount:18000,paid:true,zones:['L:Pięta']};
 await t.test('dokumentacja kończy wizytę i zachowuje snapshot',async()=>{await action('encounter',encounter);await action('patient',{id:patient,name:'Zmienione Dane',profile:{allergies:'Nowe dane'}});const v=(await pg.query('select * from podo_encounters')).rows[0];assert.equal(v.profile_snapshot.allergies,'lateks');assert.equal((await pg.query('select status from podo_appointments where id=$1',[a2])).rows[0].status,'completed');});
 await t.test('nie można nadpisać ani usunąć dokumentacji',async()=>{await assert.rejects(pg.query('update podo_encounters set observations=$1',['Nadpisanie']),/niezmienne/);await assert.rejects(pg.query('delete from podo_encounters'),/niezmienne/);});
 await t.test('uzupełnienie to nowy wpis bez modyfikacji oryginału',async()=>{await action('encounter',{...encounter,id:crypto.randomUUID(),appointment_id:null,amends_id:encounter.id,amount:0});assert.equal((await pg.query('select count(*)::int n from podo_encounters')).rows[0].n,2);});
 await t.test('anon i authenticated nie mają dostępu do tabel ani RPC',async()=>{for(const role of ['anon','authenticated']){await pg.exec(`set role ${role}`);await assert.rejects(pg.query('select * from podo_patients'),/permission denied/);await assert.rejects(action('patient',{id:patient,name:'Błąd'}),/permission denied/);await pg.exec('reset role');}});
 await t.test('claim poczty nie dubluje lease',async()=>{const first=await pg.query('select * from podo_claim_mail()');const second=await pg.query('select * from podo_claim_mail()');assert(first.rows.length>0);assert.equal(second.rows.length,0);});
 await pg.close();
});
