import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {dayKey,shiftDay} from '../assets/domain.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE):'playwright');
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXE?{executablePath:process.env.BROWSER_EXE}:{})});
const outputs=resolve('../../outputs');await mkdir(outputs,{recursive:true});
const errors=[],checks=[];
const page=await browser.newPage({viewport:{width:1440,height:1080}});page.on('pageerror',e=>errors.push(e.message));
const base=process.env.PREVIEW_URL||'http://127.0.0.1:4173';
const saved=async()=>{await page.waitForFunction(()=>!document.querySelector('dialog').open);await page.waitForFunction(()=>!document.body.classList.contains('busy'));};
const wizardTo=async(p,key)=>{for(let i=0;i<20;i++){const active=p.locator('#patient-form [data-wizard-step].active');if(await active.getAttribute('data-wizard-step')===key)return active;await p.locator('#patient-step-next').click();}throw Error(`Nie osiągnięto kroku ${key}`);};
try{
 await page.goto(base+'/?demo=1&generic=1');await page.getByRole('heading',{name:'Dzień dobry w PodoCare'}).waitFor();
 await page.screenshot({path:resolve(outputs,'podocare-pulpit.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('Pulpit desktop bez błędów i poziomego przewijania');
 await page.locator('nav a[href="#patients"]').click();await page.locator('[data-new-patient]').click();
 await page.screenshot({path:resolve(outputs,'podocare-kreator-pacjenta.png'),fullPage:true});assert.equal(await page.locator('#patient-form [data-wizard-step].active').count(),1);checks.push('Kreator pokazuje tylko jeden etap formularza');
 await page.locator('#patient-step-next').click();await page.locator('#patient-form [name="name"]').fill('Sara Testowa');await page.locator('#patient-step-next').click();await page.locator('[name="email"]').fill('sara@example.invalid');await page.locator('#patient-step-next').click();
 await page.locator('[name="diabetes"]').selectOption('yes');await page.locator('#patient-step-next').click();await page.locator('#patient-step-next').click();await page.locator('[name="allergies"]').fill('Lateks — wpis testowy');await page.locator('#patient-step-next').click();await page.locator('[name="complaints"]').fill('Sucha skóra pięt — fikcyjne dane.');
 await page.locator('#patient-step-next').click();await page.locator('#patient-step-next').click();await page.locator('#patient-step-next').click();
 await page.locator('#patient-form button[type="submit"]').click();await saved();
 await page.locator('#patient-search').fill('Sara');assert.equal(await page.locator('.patient-card').count(),1);await page.locator('.patient-card').click();await page.getByRole('heading',{name:'Sara Testowa'}).waitFor();checks.push('Dodanie, wyszukanie i otwarcie pacjenta');
 const photo=await readFile(new URL('../assets/icon-512.png',import.meta.url));
 await page.locator('[data-photo-input]').first().setInputFiles({name:'zdjecie-testowe.png',mimeType:'image/png',buffer:photo});
 await page.getByRole('heading',{name:'Potwierdź przypisanie zdjęcia'}).waitFor();assert((await page.locator('#photo-confirm-patient').innerText()).includes('Sara Testowa'));await page.locator('[data-confirm-photo]').click();
 await page.waitForFunction(()=>document.querySelector('.photo-card img')?.naturalWidth>0);assert.equal(await page.locator('.photo-card').count(),1);checks.push('Automatyczny zapis zdjęcia do wybranej karty');
 await page.locator('[data-encounter]').click();await page.locator('[name="observations"]').fill('Obserwacja testowa: sucha skóra pięty.');await page.locator('[name="performed"]').fill('Wizyta demonstracyjna.');await page.locator('[name="aftercare"]').fill('Zalecenia testowe przekazane pacjentce.');
 await page.locator('input[name="zones"][value="L:Pięta"]').check();await page.locator('[name="pain"]').selectOption('3');await page.locator('[name="amount"]').fill('150');await page.locator('[name="paid"]').check();await page.locator('[name="followup_date"]').fill(shiftDay(dayKey(),14));
 await page.locator('#encounter-form button[type="submit"]').click();await saved();await page.locator('[data-patient-tab="history"]').click();assert(await page.locator('.history-entry').innerText().then(t=>t.includes('Zalecenia testowe')));checks.push('Dokumentacja, lokalizacja zmiany i kontrola');
 await page.locator('[data-patient-tab="profile"]').click();await page.locator('[data-edit-patient]').click();await wizardTo(page,'medical-notes');await page.locator('[name="allergies"]').fill('Zmieniony wywiad');await page.locator('#patient-save-now').click();await saved();await page.locator('[data-patient-tab="history"]').click();await page.locator('summary').click();assert((await page.locator('.snapshot').innerText()).includes('Lateks — wpis testowy'));checks.push('Migawka poprzedniego wywiadu nie została nadpisana');
 await page.locator('nav a[href="#calendar"]').click();await page.locator('.topbar [data-book]').click();const tomorrow=shiftDay(dayKey(),2);await page.locator('#range-day').fill(tomorrow);await page.locator('#range-day').dispatchEvent('change');
 const a=await page.locator('[data-cell="0"]').boundingBox(),b=await page.locator('[data-cell="2"]').boundingBox();await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:8});await page.mouse.up();
 assert((await page.locator('#range-summary').innerText()).includes('90 minut'));await page.locator('#range-next').click();await page.locator('[name="patient_id"]').selectOption({label:'Sara Testowa'});await page.locator('[name="service_id"]').selectOption('basic');await page.locator('#booking-form button[type="submit"]').click();await saved();
 await page.locator(`[data-day="${tomorrow}"]`).click();assert.equal(await page.locator('.appointment-row').count(),1);await page.locator('.appointment-row').click();assert((await page.locator('dialog').innerText()).includes('08:00–09:30'));checks.push('Przeciągnięcie 90 minut tworzy jedną wizytę');
 await page.locator('[data-cancel-appointment]').click();await page.locator('#confirm-cancel').click();await saved();assert((await page.locator('.appointment-row').innerText()).includes('Anulowana'));checks.push('Anulowanie wizyty zachowuje historię');
 await page.locator('nav a[href="#settings"]').click();assert.equal(await page.locator('.settings-tools a').count(),2);assert.equal(await page.locator('nav a[href="#services"],nav a[href="#finance"],nav a[href="#ideas"],nav a[href="#advisor"]').count(),0);await page.locator('.settings-tools a[href="#settings/services"]').click();await page.locator('.service-row[data-service="basic"]').click();await page.locator('[name="price"]').fill('195');await page.locator('#service-form button[type="submit"]').click();await saved();assert.equal(await page.locator('.service-row').count(),9);assert((await page.locator('.service-row[data-service="basic"]').innerText()).includes('195'));checks.push('Zabiegi i rozliczenia w Ustawieniach, bez zakładek Pomysły i Doradca');
 await page.locator('nav a[href="#patients"]').click();await page.locator('#patient-search').fill('Anna');await page.locator('.patient-card').click();await page.getByRole('heading',{name:'Anna Nowak'}).waitFor();assert.equal(await page.locator('.photo-card').count(),0);checks.push('Zdjęcie innego pacjenta nie pojawia się w tej karcie');
 await page.screenshot({path:resolve(outputs,'podocare-karta-pacjenta.png'),fullPage:true});
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));
 await mp.goto(base+'/?demo=1&generic=1#patient/p1');await mp.getByRole('heading',{name:'Anna Nowak'}).waitFor();assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mp.screenshot({path:resolve(outputs,'podocare-telefon.png'),fullPage:true});
 assert.equal(await mp.locator('[capture="environment"]').count(),1);checks.push('Telefon: karta pacjenta, aparat, brak overflow');
 await mp.locator('nav a[href="#patients"]').click();await mp.locator('[data-new-patient]').click();assert.equal(await mp.locator('#patient-form [data-wizard-step].active').count(),1);assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mp.screenshot({path:resolve(outputs,'podocare-kreator-telefon.png'),fullPage:true});await mp.locator('[data-close]').first().click();checks.push('Telefon: kreator jednego kroku bez poziomego przewijania');
 await mp.goto(base+'/?demo=1&generic=1#patient/p1');await mp.getByRole('heading',{name:'Anna Nowak'}).waitFor();
 await mp.locator('[data-book-patient]').click();await mp.locator('#range-day').fill(tomorrow);await mp.locator('#range-day').dispatchEvent('change');await mp.locator('[data-cell="0"]').scrollIntoViewIfNeeded();
 const ma=await mp.locator('[data-cell="0"]').boundingBox(),mb=await mp.locator('[data-cell="1"]').boundingBox(),cdp=await mobile.newCDPSession(mp);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:ma.x+ma.width/2,y:ma.y+ma.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:mb.x+mb.width/2,y:mb.y+mb.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert((await mp.locator('#range-summary').innerText()).includes('60 minut'));checks.push('Dotyk: przeciągnięcie wybiera jeden zakres');
 await mp.screenshot({path:resolve(outputs,'podocare-rezerwacja-telefon.png'),fullPage:true});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));
} catch(e){console.log(JSON.stringify({errors,body:(await page.locator('body').innerText()).slice(0,3500)},null,2));await page.screenshot({path:resolve(outputs,'podocare-qa-error.png'),fullPage:true});throw e;} finally{await browser.close();}
